### ISSUE TITLE
Crédito pelo código!

### ISSUE THREAD

**Issue by diorgesl** [remontti/php-cgnat-netmap-routeros#1]
Infelizmente todo dia vemos isso, alguém copia seu código (muda umas variáveis) e nem da o crédito.

**Comment by remontti** [comment]
O código foi todo remodelado praticamente com a ideia de rodar em um webserver. Além do mais seu co código tb é uma "cópia".  Posso incluir no redame  que teve inspiração no "seu", mas crédito pelo código nada tem nada haver. Desculpa se ficouofendido por isso. A ideia e ajudar as pessoas criarem a coisa certa, mas pelo visto os "consultores" se ofendem quando alguém ajuda.

**Comment by remontti** [comment]
Diorges Rocha - Consultor de TI - Nativa Network
Quer um conselho? Cresce intelectualmente! Abraço

**Comment by diorgesl** [comment]
kkkk, baseado nisso você diz que sou consultor? Infelizmente o mundo ta cheio de aproveitadores como você, mais um batata no mundo que não consegue nem dar crédito para os outros, eu ficaria com vergonha se fosse você, mas boa sorte ai cara, você é um baita profissional! Parabéns!

**Comment by remontti** [comment]
Tá lá o crédito que vc tanto queria! Dorme na paz! 
Não vou baixar o nível com esse tipo de pessoa. 
O batata aqui já ajudou milhares de pessoas, e vc contribuiu com o quê? Nunca ouvi falar de ti. Ah cara me desculpe mas vai achar o q fazer em vez de vir aziar pq tem meia dúzia de coisas no código com base no "teu" script de cgnat, sendo q tem uma porra de lógica para tal... vai lá site da Mikrotik e pede para por lá TB. Tnc paciência tem limite. P* cara chato vc. Que me criticar vai lá no meu grupo do telegram.
